info:
  contact: {}
paths:
  /record/{some_id}:
    get:
      consumes:
      - application/json
      description: get record by ID
      parameters:
      - description: userId
        in: path
        name: some_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
swagger: "2.0"
